//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace dynamic_portfolio
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtUser;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUser;

        protected global::System.Web.UI.WebControls.TextBox txtPass;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPass;

        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}